# Generated by Django 6.1 on 2026-10-09 19:37

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OnlyToursApp', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('AttractionID', models.AutoField(help_text='Unique ID for the attraction', primary_key=True, serialize=False)),
                ('Name', models.CharField(help_text='Enter the name of the attraction', max_length=200)),
                ('Description', models.TextField(help_text='Enter a description of the attraction')),
                ('Region', models.CharField(help_text='Enter the region of the attraction', max_length=100)),
                ('IsFeatured', models.BooleanField(default=False, help_text='Indicate whether the attraction is featured')),
                ('Longitude', models.DecimalField(decimal_places=7, help_text='Enter the longitude of the attraction', max_digits=10)),
                ('Latitude', models.DecimalField(decimal_places=7, help_text='Enter the latitude of the attraction', max_digits=10)),
                ('Distance', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the distance to the attraction', max_digits=10, null=True)),
                ('DifficultyLevel', models.CharField(blank=True, choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('DIFFICULT', 'Difficult')], help_text='Select the difficulty level of the attraction', max_length=50, null=True)),
                ('Type', models.CharField(help_text='Enter the type of attraction', max_length=100)),
                ('DateAdded', models.DateField(help_text='Enter the date the attraction was added')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('PhoneNumber', models.CharField(blank=True, help_text='Enter a Phone Number', max_length=12, null=True)),
                ('CountryOfOrigin', models.CharField(help_text='Enter your Country of Origin', max_length=50)),
                ('PrimaryLanguage', models.CharField(help_text='Enter your Primary Language', max_length=30)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TourGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, help_text='Enter your First Name', max_length=200, null=True)),
                ('Surname', models.CharField(blank=True, help_text='Enter your Surname', max_length=200, null=True)),
                ('Email', models.EmailField(help_text='Enter an Email address', max_length=100, unique=True)),
                ('DateRegistered', models.DateField()),
                ('PhoneNumber', models.CharField(blank=True, help_text='Enter a Phone Number', max_length=12, null=True)),
                ('YearsofExperience', models.IntegerField(blank=True, help_text='Enter your Years of Experience', null=True)),
                ('PrimaryLanguage', models.CharField(blank=True, help_text='Enter your Primary Language', max_length=30, null=True)),
                ('Biography', models.CharField(blank=True, help_text='Enter a biography of yourself', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeRequested', models.DateTimeField()),
                ('TourDate', models.DateField()),
                ('TotalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('NumberOfParticipants', models.IntegerField(blank=True, help_text='Enter the Number of Participants', null=True)),
                ('BookingStatus', models.CharField(choices=[('PAID', 'paid'), ('UNPAID', 'unpaid')], max_length=20)),
                ('Customer', models.ForeignKey(help_text='Choose a Customer', on_delete=django.db.models.deletion.CASCADE, to='OnlyToursApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTravelPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TravelPreferences', models.CharField(blank=True, max_length=30, null=True)),
                ('Customer', models.ForeignKey(help_text='Choose a Customer', on_delete=django.db.models.deletion.CASCADE, to='OnlyToursApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LanguagesSpoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(blank=True, help_text='Enter a language', max_length=30, null=True)),
                ('Guide', models.ForeignKey(help_text='Choose a Guide', on_delete=django.db.models.deletion.CASCADE, to='OnlyToursApp.tourguide')),
            ],
        ),
    ]
